language: java
jdk:
  - oraclejdk8

install: gradle test

notifications:
  email:
    recipients:
      - ranevesmotox@gmail.com
      - rjesus@thoughtworks.com
    on_success: never
    on_failure: always